# Generated by Django 4.0.2 on 2022-02-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Fish',
        ),
    ]
