# Generated by Django 4.0.2 on 2022-02-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_rename_item_fish'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
